### ISSUE TITLE
Unable to open file: name = 'weights/weights_ssd300.hdf5'

### ISSUE THREAD

**Issue by GonzaBCCC** [vsegura93/mcv-m5#3]
Since we've had so many problems integrating SSD to the workspace, this has come down to being the last error in the attempts to do the implementation:

master@mastergpu07:~/workspace/mcv-m5/code/week3_4/taskD$ bash run_ssd.sh
master@mastergpu07:~/workspace/mcv-m5/code/week3_4/taskD$ Using TensorFlow backend.
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
Traceback (most recent call last):
  File "../../train.py", line 122, in <module>
    main()
  File "../../train.py", line 114, in main
    process(cf)
  File "../../train.py", line 33, in process
    model = Model_Factory().make(cf, optimizer)
  File "/home/master/workspace/mcv-m5/code/models/model_factory.py", line 113, in make
    model = self.make_one_net_model(cf, in_shape, loss, metrics, optimizer)
  File "/home/master/workspace/mcv-m5/code/models/model_factory.py", line 195, in make_one_net_model
    freeze_layers_from='base_model')
  File "/home/master/workspace/mcv-m5/code/models/ssd.py", line 34, in build_ssd
    model.load_weights('weights/weights_SSD300.hdf5',by_name=True)
  File "/home/master/.local/lib/python2.7/site-packages/Keras-1.2.2-py2.7.egg/keras/engine/topology.py", line 2702, in load_weights
    f = h5py.File(filepath, mode='r')
  File "/home/master/.local/lib/python2.7/site-packages/h5py/_hl/files.py", line 272, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/home/master/.local/lib/python2.7/site-packages/h5py/_hl/files.py", line 92, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/tmp/pip-4rPeHA-build/h5py/_objects.c:2684)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/tmp/pip-4rPeHA-build/h5py/_objects.c:2642)
  File "h5py/h5f.pyx", line 76, in h5py.h5f.open (/tmp/pip-4rPeHA-build/h5py/h5f.c:1930)
IOError: Unable to open file (Unable to open file: name = 'weights/weights_ssd300.hdf5', errno = 2, error message = 'no such file or directory', flags = 0, o_flags = 0)

**Comment by GonzaBCCC** [comment]
already fixed
